package render

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/vnoiram/linux-nixer/internal/model"
)

func Project(out string, report model.ScanReport) error {
	dirs := []string{
		out,
		filepath.Join(out, "hosts", "generated"),
		filepath.Join(out, "users"),
		filepath.Join(out, "modules"),
		filepath.Join(out, "reports"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	host := report.Host.Hostname
	if host == "" {
		host = "generated"
	}
	files := map[string]string{
		"flake.nix":                         renderTemplate(flakeTemplate, data{Host: host, Report: report}),
		"hosts/generated/configuration.nix": renderTemplate(hostTemplate, data{Host: host, Report: report}),
		"users/home.nix":                    renderTemplate(homeTemplate, data{Host: host, Report: report}),
		"modules/containers.nix":            renderTemplate(containersTemplate, data{Host: host, Report: report}),
		"reports/migration-report.md":       renderReport(report),
	}
	for rel, content := range files {
		if err := os.WriteFile(filepath.Join(out, rel), []byte(content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

type data struct {
	Host   string
	Report model.ScanReport
}

func renderTemplate(tpl string, d data) string {
	t := template.Must(template.New("nix").Funcs(template.FuncMap{
		"nixList":        nixList,
		"quote":          quote,
		"systemPackages": packageNames,
	}).Parse(tpl))
	var buf bytes.Buffer
	if err := t.Execute(&buf, d); err != nil {
		panic(err)
	}
	return buf.String()
}

func nixList(values []string) string {
	if len(values) == 0 {
		return "[ ]"
	}
	sort.Strings(values)
	var b strings.Builder
	b.WriteString("[\n")
	for _, v := range values {
		b.WriteString("    ")
		b.WriteString(v)
		b.WriteString("\n")
	}
	b.WriteString("  ]")
	return b.String()
}

func quote(s string) string {
	return fmt.Sprintf("%q", s)
}

func packageNames(report model.ScanReport) []string {
	seen := map[string]bool{}
	var names []string
	for _, pkg := range report.Packages {
		if pkg.Decision != model.DecisionConfirmed && pkg.Decision != model.DecisionCandidate {
			continue
		}
		if len(pkg.NixNames) == 0 {
			continue
		}
		name := "pkgs." + pkg.NixNames[0]
		if !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	return names
}

func renderReport(report model.ScanReport) string {
	var b strings.Builder
	b.WriteString("# linux-nixer migration report\n\n")
	b.WriteString("## Host\n\n")
	b.WriteString(fmt.Sprintf("- Distro: %s %s\n", report.Host.Distro, report.Host.Release))
	b.WriteString(fmt.Sprintf("- Hostname: %s\n\n", report.Host.Hostname))
	b.WriteString("## Package candidates\n\n")
	for _, pkg := range report.Packages {
		b.WriteString(fmt.Sprintf("- `%s` via %s", pkg.Name, pkg.Manager))
		if len(pkg.NixNames) > 0 {
			b.WriteString(fmt.Sprintf(" -> `%s`", pkg.NixNames[0]))
		}
		b.WriteString("\n")
	}
	b.WriteString("\n## Filesystem findings\n\n")
	for _, f := range report.FilesystemDiff {
		b.WriteString(fmt.Sprintf("- `%s` %s %s\n", f.Path, f.Type, f.Reason))
	}
	b.WriteString("\n## Stateful data and manual migration notes\n\n")
	for _, f := range report.StatefulData {
		b.WriteString(fmt.Sprintf("- `%s` %s\n", f.Path, f.Reason))
	}
	for _, item := range report.Items {
		if item.Decision == model.DecisionTODO || item.Decision == model.DecisionMigrationNote || item.Decision == model.DecisionCandidate {
			b.WriteString(fmt.Sprintf("- `%s` %s %s\n", item.Path, item.Kind, item.Reason))
		}
	}
	if len(report.Warnings) > 0 {
		b.WriteString("\n## Warnings\n\n")
		for _, w := range report.Warnings {
			b.WriteString(fmt.Sprintf("- %s: %s\n", w.Source, w.Message))
		}
	}
	return b.String()
}

var flakeTemplate = `{
  description = "Generated by linux-nixer";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = { self, nixpkgs, home-manager, ... }: {
    nixosConfigurations.{{ .Host }} = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./hosts/generated/configuration.nix
        home-manager.nixosModules.home-manager
        {
          home-manager.useGlobalPkgs = true;
          home-manager.useUserPackages = true;
          home-manager.users.generated = import ./users/home.nix;
        }
      ];
    };
  };
}
`

var hostTemplate = `# Generated by linux-nixer. Review before applying.
{ config, pkgs, ... }:

{
  networking.hostName = {{ quote .Report.Host.Hostname }};
  time.timeZone = "UTC";

  environment.systemPackages = with pkgs; {{ nixList (systemPackages .Report) }};

  imports = [
    ../../modules/containers.nix
  ];
}
`

var homeTemplate = `# Generated by linux-nixer. Review before applying.
{ config, pkgs, ... }:

{
  home.username = "generated";
  home.homeDirectory = "/home/generated";
  home.stateVersion = "24.05";
  programs.home-manager.enable = true;
}
`

var containersTemplate = `# Generated by linux-nixer. Container details are reported in reports/migration-report.md.
{ config, pkgs, ... }:

{
  virtualisation.docker.enable = true;
  virtualisation.podman.enable = true;
}
`
