// embedded.go bundles pre-built baseline manifests for the curated
// catalog's distro/release pairs directly into this binary, so a
// fully offline host with neither Docker/Podman nor network access can
// still get a real baseline for a common release without a separate
// download step. Generated with a real `baseline fetch` run against the
// catalog's actual images — never hand-written — and gzip-compressed
// (real files, not synthesized data, so they compress far better than
// random bytes: ~130KB per Ubuntu release, ~270-290KB per Debian release).
//
// See DESIGN_AND_ROADMAP.md's "Baseline catalog maintenance" section for
// the review checklist to follow when adding a new bundled entry.
package baseline

import (
	"bytes"
	"compress/gzip"
	"embed"
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

//go:embed baselines_data/*.json.gz
var bundledManifests embed.FS

// BundledManifest returns the pre-built manifest bundled into this binary
// for a distro/release pair, or nil, false if none is bundled. It never
// touches the network or a container backend.
func BundledManifest(distro, release string) (*Manifest, bool, error) {
	distro = strings.ToLower(strings.TrimSpace(distro))
	release = strings.TrimSpace(release)
	if distro == "" || release == "" {
		return nil, false, nil
	}
	name := fmt.Sprintf("baselines_data/%s-%s.json.gz", distro, release)
	compressed, err := bundledManifests.ReadFile(name)
	if err != nil {
		return nil, false, nil
	}
	gz, err := gzip.NewReader(bytes.NewReader(compressed))
	if err != nil {
		return nil, false, fmt.Errorf("decompressing bundled manifest for %s:%s: %w", distro, release, err)
	}
	defer gz.Close()
	data, err := io.ReadAll(gz)
	if err != nil {
		return nil, false, fmt.Errorf("decompressing bundled manifest for %s:%s: %w", distro, release, err)
	}
	var manifest Manifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return nil, false, fmt.Errorf("parsing bundled manifest for %s:%s: %w", distro, release, err)
	}
	// Rewrite Source for provenance: it was generated by a real fetch at
	// bundling time (see baselines_data/ package doc), not by a live pull
	// just now, and callers/reports shouldn't be misled into thinking one
	// happened.
	manifest.Source = "bundled:" + manifest.Source
	return &manifest, true, nil
}
